name: Custom CI
on:
  pull_request:
    branches:
      - main
jobs:
  show-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Show Terraform version
        run: curl --version
      - name: Show Pull Request Info
        run: |
          echo """
            The pull request title is: ${{ github.event.pull_request.title }}
            and it is from ${{ github.head_ref }} to ${{ github.base_ref }}
          """