name: Custom CI
on:
  pull_request:
    branches:
      - main
jobs:
  show-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - if: ${{ env.ACT }}
        name: Only on ACT
        run: echo "Hello I'm running on ACT!"
      - name: install curl
        run: sudo apt-get install -y curl
      - name: Show curl version
        run: curl --version
      - name: Show Pull Request Info
        run: |
          echo """
            The pull request title is: ${{ github.event.pull_request.title }}
            and it is from ${{ github.head_ref }} to ${{ github.base_ref }}
          """